const text = {
  "epaper.naidunia.com": {
    title: "NaiDunia Epaper: Daily MP Newspaper and Chhattisgarh News Paper Online",
    mySubscription: "मेरा एक्टिव सब्सक्रिप्शन",
    cancelAutoRenew: "कैंसल ऑटो-रिन्यू",
    cancelled: "कैंसिल्ड",
    startDate: "प्रारंभ तिथि",
    endDate: "समाप्ति तिथि",
    remainingFreeTrial: "बचा हुआ फ्री ट्रायल समय",
    days: "दिन",
    txnId: "ट्रांज़ैक्शन आईडी",
    bundlePackage: "बंडल पैकेज",
    activePlanBenefits: "एक्टिव प्लान में मिल रहे फ़ायदे",
    noActiveSubscription: "आपका कोई सब्सक्रिप्शन एक्टिव नहीं है",
    purchasePlanPrompt: "प्रीमियम अनुभव पाने के लिए हमारे प्लान ख़रीदें।",
    browsePlans: "उपलब्ध प्लान देखें",
    transactionDetails: "ट्रांज़ैक्शन डिटेल्स",
    orderedOn: "ऑर्डर किया गया",
    orderStatus: "ऑर्डर स्थिति",
    noTransactions: "आपकी कोई ट्रांज़ैक्शन नहीं है।",
    transactionHistoryPrompt: "कोई प्लान खरीदने के बाद आपकी ट्रांज़ैक्शन हिस्ट्री यहां दिखाई देगी।",
    copyTransactionId: "ट्रांज़ैक्शन आईडी कॉपी करें",
    // New keys for EditProfile
    addMobileNumber: "अपना मोबाइल नंबर जोड़ें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    birthday: "जन्मदिन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    country: "देश / क्षेत्र",
    state: "राज्य",
    city: "शहर",
    selectCountry: "देश चुनें",
    selectState: "राज्य चुनें",
    selectCity: "शहर चुनें",
    saveInformation: "जानकारी सहेजें",
    deleteAccount: "अपना खाता हटाएं",
    deleteAccountPrompt: "इस खाते से संबंधित सभी जानकारी हटाएं।",
    joinedSince: "से सदस्य बने",
    somethingWentWrong: "कुछ गलत हो गया",
  },
  "epaper.jagran.com": {
    title: "Dainik Jagran ePaper: Hindi News Paper, Today Newspaper, Online Hindi Epaper",
    mySubscription: "मेरा एक्टिव सब्सक्रिप्शन",
    cancelAutoRenew: "कैंसल ऑटो-रिन्यू",
    cancelled: "कैंसिल्ड",
    startDate: "प्रारंभ तिथि",
    endDate: "समाप्ति तिथि",
    remainingFreeTrial: "बचा हुआ फ्री ट्रायल समय",
    days: "दिन",
    txnId: "ट्रांज़ैक्शन आईडी",
    bundlePackage: "बंडल पैकेज",
    activePlanBenefits: "एक्टिव प्लान में मिल रहे फ़ायदे",
    noActiveSubscription: "आपका कोई सब्सक्रिप्शन एक्टिव नहीं है",
    purchasePlanPrompt: "प्रीमियम अनुभव पाने के लिए हमारे प्लान ख़रीदें।",
    browsePlans: "उपलब्ध प्लान देखें",
    transactionDetails: "ट्रांज़ैक्शन डिटेल्स",
    orderedOn: "ऑर्डर किया गया",
    orderStatus: "ऑर्डर स्थिति",
    noTransactions: "आपकी कोई ट्रांज़ैक्शन नहीं है।",
    transactionHistoryPrompt: "कोई प्लान खरीदने के बाद आपकी ट्रांज़ैक्शन हिस्ट्री यहां दिखाई देगी।",
    copyTransactionId: "ट्रांज़ैक्शन आईडी कॉपी करें",
    // New keys for EditProfile
    addMobileNumber: "अपना मोबाइल नंबर जोड़ें",
    firstName: "पहला नाम",
    lastName: "अंतिम नाम",
    birthday: "जन्मदिन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    country: "देश / क्षेत्र",
    state: "राज्य",
    city: "शहर",
    selectCountry: "देश चुनें",
    selectState: "राज्य चुनें",
    selectCity: "शहर चुनें",
    saveInformation: "जानकारी सहेजें",
    deleteAccount: "अपना खाता हटाएं",
    deleteAccountPrompt: "इस खाते से संबंधित सभी जानकारी हटाएं।",
    joinedSince: "से सदस्य बने",
    somethingWentWrong: "कुछ गलत हो गया",
  },
  "epaper.punjabijagran.com": {
    title: "Punjabi Jagran ePaper: Read Latest Punjabi ePaper News, Online Punjabi ePaper News",
    desc: "Punjabi Jagran E paper - Digital Edition of Punjabi News Paper which is being circulated Amritsar, Bathinda, Chandigarh, Doaba, Gurdaspur, Jalandhar, Kapurthala, Ludhiana, Malwa, Patiala, and other cities of Punjab is available online also.",
    mySubscription: "ਮੇਰਾ ਐਕਟਿਵ ਸਬਸਕ੍ਰਿਪਸ਼ਨ",
    cancelAutoRenew: "ਕੈਂਸਲ ਆਟੋ-ਰੀਨਿਊ",
    cancelled: "ਕੈਂਸਲ ਕੀਤਾ",
    startDate: "ਸ਼ੁਰੂਆਤੀ ਮਿਤੀ",
    endDate: "ਅੰਤਿਮ ਮਿਤੀ",
    remainingFreeTrial: "ਬਾਕੀ ਮੁਫਤ ਟਰਾਇਲ ਸਮਾਂ",
    days: "ਦਿਨ",
    txnId: "ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਆਈਡੀ",
    bundlePackage: "ਬੰਡਲ ਪੈਕੇਜ",
    activePlanBenefits: "ਐਕਟਿਵ ਪਲੈਨ ਵਿੱਚ ਮਿਲ ਰਹੇ ਫਾਇਦੇ",
    noActiveSubscription: "ਤੁਹਾਡਾ ਕੋਈ ਸਬਸਕ੍ਰਿਪਸ਼ਨ ਐਕਟਿਵ ਨਹੀਂ ਹੈ",
    purchasePlanPrompt: "ਪ੍ਰੀਮੀਅਮ ਅਨੁਭਵ ਪ੍ਰਾਪਤ ਕਰਨ ਲਈ ਸਾਡੇ ਪਲੈਨ ਖਰੀਦੋ।",
    browsePlans: "ਉਪਲਬਧ ਪਲੈਨ ਵੇਖੋ",
    transactionDetails: "ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਵੇਰਵੇ",
    orderedOn: "ਆਰਡਰ ਕੀਤਾ ਗਿਆ",
    orderStatus: "ਆਰਡਰ ਸਥਿਤੀ",
    noTransactions: "ਤੁਹਾਡੀ ਕੋਈ ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਨਹੀਂ ਹੈ।",
    transactionHistoryPrompt: "ਕੋਈ ਪਲੈਨ ਖਰੀਦਣ ਤੋਂ ਬਾਅਦ ਤੁਹਾਡੀ ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਹਿਸਟਰੀ ਇੱਥੇ ਵਿਖਾਈ ਦੇਵੇਗੀ।",
    copyTransactionId: "ਟ੍ਰਾਂਜ਼ੈਕਸ਼ਨ ਆਈਡੀ ਕਾਪੀ ਕਰੋ",
    // New keys for EditProfile
    addMobileNumber: "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਜੋੜੋ",
    firstName: "ਪਹਿਲਾ ਨਾਮ",
    lastName: "ਆਖਰੀ ਨਾਮ",
    birthday: "ਜਨਮਦਿਨ",
    gender: "ਲਿੰਗ",
    male: "ਮਰਦ",
    female: "ਔਰਤ",
    country: "ਦੇਸ਼ / ਖੇਤਰ",
    state: "ਰਾਜ",
    city: "ਸ਼ਹਿਰ",
    selectCountry: "ਦੇਸ਼ ਚੁਣੋ",
    selectState: "ਰਾਜ ਚੁਣੋ",
    selectCity: "ਸ਼ਹਿਰ ਚੁਣੋ",
    saveInformation: "ਜਾਣਕਾਰੀ ਸੁਰੱਖਿਅਤ ਕਰੋ",
    deleteAccount: "ਆਪਣਾ ਖਾਤਾ ਹਟਾਓ",
    deleteAccountPrompt: "ਇਸ ਖਾਤੇ ਨਾਲ ਸੰਬੰਧਿਤ ਸਾਰੀ ਜਾਣਕਾਰੀ ਹਟਾਓ।",
    joinedSince: "ਤੋਂ ਮੈਂਬਰ ਬਣੇ",
    somethingWentWrong: "ਕੁਝ ਗਲਤ ਹੋ ਗਿਆ",
  },
};

export const getAccountText = (domain) => {
  return text[domain] || text["epaper.jagran.com"]; // Fallback to a default domain
};