const text = {
  "epaper.naidunia.com": {
    title: "NaiDunia Epaper: Daily MP Newspaper and Chhattisgarh News Paper Online",
    welcome: "स्वागत है",
    reader: "पाठक",
    newTicket: "नई टिकट बनाएँ",
    myTickets: "मेरी टिकट्स",
    firstNameRequired: "पहला नाम आवश्यक है",
    lastNameRequired: "अंतिम नाम आवश्यक है",
    emailRequired: "ईमेल आवश्यक है",
    invalidEmail: "कृपया एक वैध ईमेल पता दर्ज करें",
    titleRequired: "शीर्षक आवश्यक है",
    categoryRequired: "श्रेणी आवश्यक है",
    descriptionRequired: "विवरण आवश्यक है",
    submitFailed: "टिकट सबमिट करने में विफल। कृपया पुनः प्रयास करें।",
    // New keys for NewTicketForm
    createSupportTicket: "सपोर्ट टिकट बनाएं",
    selectCategoryInstruction: "अपनी समस्या के हिसाब से नीचे दी गई कैटेगरी चुनें और बाकी जानकारी भरें।",
    firstNameLabel: "पहला नाम *",
    lastNameLabel: "आख़िरी नाम *",
    emailLabel: "ईमेल *",
    mobileNumberLabel: "मोबाइल नंबर",
    addMobileNumber: "अपना मोबाइल नंबर जोड़े",
    titleLabel: "टाइटल *",
    descriptionLabel: "समस्या का पूरा विवरण *",
    addPhotosLabel: "फोटो जोड़ें (ज़्यादा से ज़्यादा 2 फोटो)",
    clickToUpload: "यहां क्लिक करके फोटो लगाएं",
    photoUploadInstruction: "10MB तक की JPG या PNG फोटो लग सकती है (2 तक)",
    submitTicket: "टिकट सबमिट करें",
    submitting: "सबमिट हो रहा है...",

    YourTicket:' आपके सपोर्ट टिकट्स',
    ticketList: 'अपनी शिकायतें देखें और अपडेट करें',
  },
  "epaper.jagran.com": {
    title: "Dainik Jagran ePaper: Hindi News Paper, Today Newspaper, Online Hindi Epaper",
    welcome: "स्वागत है",
    reader: "पाठक",
    newTicket: "नई टिकट बनाएँ",
    myTickets: "मेरी टिकट्स",
    firstNameRequired: "पहला नाम आवश्यक है",
    lastNameRequired: "अंतिम नाम आवश्यक है",
    emailRequired: "ईमेल आवश्यक है",
    invalidEmail: "कृपया एक वैध ईमेल पता दर्ज करें",
    titleRequired: "शीर्षक आवश्यक है",
    categoryRequired: "श्रेणी आवश्यक है",
    descriptionRequired: "विवरण आवश्यक है",
    submitFailed: "टिकट सबमिट करने में विफल। कृपया पुनः प्रयास करें।",
    // New keys for NewTicketForm
    createSupportTicket: "सपोर्ट टिकट बनाएं",
    selectCategoryInstruction: "अपनी समस्या के हिसाब से नीचे दी गई कैटेगरी चुनें और बाकी जानकारी भरें।",
    firstNameLabel: "पहला नाम *",
    lastNameLabel: "आख़िरी नाम *",
    emailLabel: "ईमेल *",
    mobileNumberLabel: "मोबाइल नंबर",
    addMobileNumber: "अपना मोबाइल नंबर जोड़े",
    titleLabel: "टाइटल *",
    descriptionLabel: "समस्या का पूरा विवरण *",
    addPhotosLabel: "फोटो जोड़ें (ज़्यादा से ज़्यादा 2 फोटो)",
    clickToUpload: "यहां क्लिक करके फोटो लगाएं",
    photoUploadInstruction: "10MB तक की JPG या PNG फोटो लग सकती है (2 तक)",
    submitTicket: "टिकट सबमिट करें",
    submitting: "सबमिट हो रहा है...",

    YourTicket:' आपके सपोर्ट टिकट्स',
    ticketList: 'अपनी शिकायतें देखें और अपडेट करें',
  },
  "epaper.punjabijagran.com": {
    title: "Punjabi Jagran ePaper: Read Latest Punjabi ePaper News, Online Punjabi ePaper News",
    desc: "Punjabi Jagran E paper - Digital Edition of Punjabi News Paper which is being circulated Amritsar, Bathinda, Chandigarh, Doaba, Gurdaspur, Jalandhar, Kapurthala, Ludhiana, Malwa, Patiala, and other cities of Punjab is available online also.",
    welcome: "ਸੁਆਗਤ ਹੈ",
    reader: "ਪਾਠਕ",
    newTicket: "ਨਵੀਂ ਟਿਕਟ ਬਣਾਓ",
    myTickets: "ਮੇਰੀਆਂ ਟਿਕਟਾਂ",
    firstNameRequired: "ਪਹਿਲਾ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ",
    lastNameRequired: "ਆਖਰੀ ਨਾਮ ਲਾਜ਼ਮੀ ਹੈ",
    emailRequired: "ਈਮੇਲ ਲਾਜ਼ਮੀ ਹੈ",
    invalidEmail: "ਕਿਰਪਾ ਕਰਕੇ ਇੱਕ ਵੈਧ ਈਮੇਲ ਪਤਾ ਦਰਜ ਕਰੋ",
    titleRequired: "ਸਿਰਲੇਖ ਲਾਜ਼ਮੀ ਹੈ",
    categoryRequired: "ਸ਼੍ਰੇਣੀ ਲਾਜ਼ਮੀ ਹੈ",
    descriptionRequired: "ਵੇਰਵਾ ਲਾਜ਼ਮੀ ਹੈ",
    submitFailed: "ਟਿਕਟ ਜਮ੍ਹਾਂ ਕਰਨ ਵਿੱਚ ਅਸਫਲ। ਕਿਰਪਾ ਕਰਕੇ ਮੁੜ ਕੋਸ਼ਿਸ਼ ਕਰੋ।",
    // New keys for NewTicketForm
    createSupportTicket: "ਸਹਾਇਤਾ ਟਿਕਟ ਬਣਾਓ",
    selectCategoryInstruction: "ਆਪਣੀ ਸਮੱਸਿਆ ਦੇ ਹਿਸਾਬ ਨਾਲ ਹੇਠਾਂ ਦਿੱਤੀ ਸ਼੍ਰੇਣੀ ਚੁਣੋ ਅਤੇ ਬਾਕੀ ਜਾਣਕਾਰੀ ਭਰੋ।",
    firstNameLabel: "ਪਹਿਲਾ ਨਾਮ *",
    lastNameLabel: "ਆਖਰੀ ਨਾਮ *",
    emailLabel: "ਈਮੇਲ *",
    mobileNumberLabel: "ਮੋਬਾਈਲ ਨੰਬਰ",
    addMobileNumber: "ਆਪਣਾ ਮੋਬਾਈਲ ਨੰਬਰ ਜੋੜੋ",
    titleLabel: "ਸਿਰਲੇਖ *",
    descriptionLabel: "ਸਮੱਸਿਆ ਦਾ ਪੂਰਾ ਵੇਰਵਾ *",
    addPhotosLabel: "ਫੋਟੋਆਂ ਜੋੜੋ (ਵੱਧ ਤੋਂ ਵੱਧ 2 ਫੋਟੋਆਂ)",
    clickToUpload: "ਇੱਥੇ ਕਲਿੱਕ ਕਰਕੇ ਫੋਟੋ ਲਗਾਓ",
    photoUploadInstruction: "10MB ਤੱਕ ਦੀ JPG ਜਾਂ PNG ਫੋਟੋ ਲਗ ਸਕਦੀ ਹੈ (2 ਤੱਕ)",
    submitTicket: "ਟਿਕਟ ਜਮ੍ਹਾਂ ਕਰੋ",
    submitting: "ਜਮ੍ਹਾਂ ਹੋ ਰਿਹਾ ਹੈ...",

    YourTicket:' ਤੁਹਾਡੇ ਸਹਾਇਤਾ ਟਿਕਟ',
    ticketList: 'ਆਪਣੀ ਸ਼ਿਕਾਇਤਾਂ ਨੂੰ ਵੇਖੋ ਅਤੇ ਅਪਡੇਟ ਕਰੋ',
  },
};

export const getSupportMeta = (domain) => {
  return text[domain] || text["epaper.jagran.com"]; // Fallback to a default domain
};
